# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saiteja/Downloads/theatre-opengl-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saiteja/Downloads/theatre-opengl-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saiteja/Downloads/theatre-opengl-master/CMakeFiles /home/saiteja/Downloads/theatre-opengl-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saiteja/Downloads/theatre-opengl-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named theatre

# Build rule for target.
theatre: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 theatre
.PHONY : theatre

# fast build rule for target.
theatre/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/build
.PHONY : theatre/fast

src/chair.o: src/chair.cpp.o
.PHONY : src/chair.o

# target to build an object file
src/chair.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chair.cpp.o
.PHONY : src/chair.cpp.o

src/chair.i: src/chair.cpp.i
.PHONY : src/chair.i

# target to preprocess a source file
src/chair.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chair.cpp.i
.PHONY : src/chair.cpp.i

src/chair.s: src/chair.cpp.s
.PHONY : src/chair.s

# target to generate assembly for a file
src/chair.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chair.cpp.s
.PHONY : src/chair.cpp.s

src/chairarm.o: src/chairarm.cpp.o
.PHONY : src/chairarm.o

# target to build an object file
src/chairarm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chairarm.cpp.o
.PHONY : src/chairarm.cpp.o

src/chairarm.i: src/chairarm.cpp.i
.PHONY : src/chairarm.i

# target to preprocess a source file
src/chairarm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chairarm.cpp.i
.PHONY : src/chairarm.cpp.i

src/chairarm.s: src/chairarm.cpp.s
.PHONY : src/chairarm.s

# target to generate assembly for a file
src/chairarm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/chairarm.cpp.s
.PHONY : src/chairarm.cpp.s

src/stair.o: src/stair.cpp.o
.PHONY : src/stair.o

# target to build an object file
src/stair.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/stair.cpp.o
.PHONY : src/stair.cpp.o

src/stair.i: src/stair.cpp.i
.PHONY : src/stair.i

# target to preprocess a source file
src/stair.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/stair.cpp.i
.PHONY : src/stair.cpp.i

src/stair.s: src/stair.cpp.s
.PHONY : src/stair.s

# target to generate assembly for a file
src/stair.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/src/stair.cpp.s
.PHONY : src/stair.cpp.s

theatre.o: theatre.cpp.o
.PHONY : theatre.o

# target to build an object file
theatre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/theatre.cpp.o
.PHONY : theatre.cpp.o

theatre.i: theatre.cpp.i
.PHONY : theatre.i

# target to preprocess a source file
theatre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/theatre.cpp.i
.PHONY : theatre.cpp.i

theatre.s: theatre.cpp.s
.PHONY : theatre.s

# target to generate assembly for a file
theatre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/theatre.dir/build.make CMakeFiles/theatre.dir/theatre.cpp.s
.PHONY : theatre.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... theatre"
	@echo "... src/chair.o"
	@echo "... src/chair.i"
	@echo "... src/chair.s"
	@echo "... src/chairarm.o"
	@echo "... src/chairarm.i"
	@echo "... src/chairarm.s"
	@echo "... src/stair.o"
	@echo "... src/stair.i"
	@echo "... src/stair.s"
	@echo "... theatre.o"
	@echo "... theatre.i"
	@echo "... theatre.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

